[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Directory to publish (build output)
  publish = "dist"
  
  # Base directory for build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Environment variables for build (v3.7.0 - Enhanced Dance Sound + Supabase Integration)
  VITE_DEBUG_MODE = "false"
  VITE_CHILD_SAFETY_MODE = "true"
  VITE_DEFAULT_USER_AGE = "12"
  NODE_ENV = "production"
  
  # Supabase Configuration (add actual values in Netlify dashboard)
  VITE_SUPABASE_URL = "https://lqxstmjczpfywfgyhahj.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

# Redirect rules for SPA (excluding API functions)
# Functions are automatically excluded from this redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  conditions = {Role = []}
  
# Ensure functions are not redirected
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://bolt.new; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; media-src 'self' blob:; connect-src 'self' https://generativelanguage.googleapis.com https://fonts.googleapis.com https://lqxstmjczpfywfgyhahj.supabase.co https://api.scripture.api.bible;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server configuration  
[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 5000
  functionsPort = 8888
  targetPort = 5173
  autoLaunch = false

# CORS headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
