[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Directory to publish (build output)
  publish = "dist"
  
  # Base directory for build
  base = "."

[build.environment]
  # Node.js version
  NODE_VERSION = "18"
  
  # Environment variables for build (v3.5.0 - Gemini Integration)
  # IMPORTANT: Add your actual API key in Netlify dashboard environment variables
  # DO NOT commit real API keys to version control
  VITE_GEMINI_API_KEY = "your_actual_gemini_api_key_here"
  VITE_DEBUG_MODE = "false"
  VITE_CHILD_SAFETY_MODE = "true"
  VITE_DEFAULT_USER_AGE = "12"
  NODE_ENV = "production"

# Redirect rules for SPA
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval'; style-src 'self' 'unsafe-inline'; img-src 'self' data: https:; font-src 'self' data:; connect-src 'self' https://generativelanguage.googleapis.com;"

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration (if using Netlify Functions)
[functions]
  directory = "netlify/functions"
