[build]
  # Build command for the frontend
  command = "npm run build"
  
  # Directory to publish (build output)
  publish = "dist"
  
  # Base directory for build
  base = "."
  
  # Build time limit (15 minutes)
  command_timeout = 900

[build.environment]
  # Node.js version
  NODE_VERSION = "20"
  
  # Environment variables for build (v3.7.0 - Enhanced Dance Sound + Supabase Integration)
  VITE_DEBUG_MODE = "false"
  VITE_CHILD_SAFETY_MODE = "true"
  VITE_DEFAULT_USER_AGE = "12"
  NODE_ENV = "production"
  
  # Supabase Configuration (add actual values in Netlify dashboard)
  VITE_SUPABASE_URL = "https://lqxstmjczpfywfgyhahj.supabase.co"
  VITE_SUPABASE_ANON_KEY = "your_supabase_anon_key_here"

# Netlify Build Plugins for Performance & Quality
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  
  [plugins.inputs]
    output_path = "reports/lighthouse.html"
    
  [plugins.inputs.thresholds]
    performance = 0.8
    accessibility = 0.9
    best-practices = 0.9
    seo = 0.9

[[plugins]]
  package = "netlify-plugin-cache"
  
  [plugins.inputs]
    paths = [
      "node_modules",
      ".npm",
      "dist"
    ]

[[plugins]]
  package = "netlify-plugin-checklinks"
  
  [plugins.inputs]
    skipPatterns = [
      "/admin",
      "/api"
    ]
    entryPoints = [
      "*.html"
    ]

# Redirect rules for SPA (functions automatically excluded by Netlify)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false

# Security & Performance headers - Enhanced for child safety
[[headers]]
  for = "/*"
  [headers.values]
    # Security Headers
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-DNS-Prefetch-Control = "on"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Permissions-Policy = "camera=(), microphone=(self), geolocation=(), payment=()"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://bolt.new; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' data: https://fonts.gstatic.com; img-src 'self' data: https:; media-src 'self' blob:; connect-src 'self' https://generativelanguage.googleapis.com https://fonts.googleapis.com https://lqxstmjczpfywfgyhahj.supabase.co https://api.scripture.api.bible;"

# Disable caching for HTML to ensure users get latest bundle references
[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Disable caching for main index
[[headers]]
  for = "/"
  [headers.values]
    Cache-Control = "no-cache, no-store, must-revalidate"

# Cache static assets (images, fonts, etc.) - 1 year
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Cache images specifically
[[headers]]
  for = "/assets/images/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
    
# Cache videos (Cavalier Spaniel videos!)
[[headers]]
  for = "/assets/videos/*"
  [headers.values]
    Cache-Control = "public, max-age=2592000, immutable"

# Cache sounds
[[headers]]
  for = "/sounds/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# JavaScript and CSS bundles
[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Functions configuration
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"

# Dev server configuration  
[dev]
  framework = "#custom"
  command = "npm run dev"
  port = 5000
  functionsPort = 8888
  targetPort = 5173
  autoLaunch = false

# CORS headers for API functions
[[headers]]
  for = "/.netlify/functions/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization"
