name: Deploy DaisyDog v1.5.0

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run safety tests
      run: npm run test:safety
      
    - name: Run local response tests
      run: npm run test:local
      
    - name: Build application
      run: npm run build
      env:
        VITE_ANTHROPIC_API_KEY: ${{ secrets.VITE_ANTHROPIC_API_KEY }}
        VITE_OPENAI_API_KEY: ${{ secrets.VITE_OPENAI_API_KEY }}
        VITE_DEBUG_MODE: false
        VITE_LOG_API_STATUS: false
        VITE_SAFETY_LEVEL: strict
        VITE_VERSION: 1.5.0
        VITE_ENVIRONMENT: production
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./dist
        cname: daisydog.ai